---
# This file defines job integration with the Packit service
# docs: https://github.com/packit-service/packit/blob/master/docs/configuration.md
specfile_path: python-pulsectl.spec

upstream_package_name: pulsectl
downstream_package_name: python-pulsectl
# Upstream currently set to fork
upstream_project_url: https://github.com/stickster/python-pulse-control

actions:
  create-archive:
  - "python3 setup.py sdist --dist-dir ."
  - "sh -c 'echo pulsectl-$(python3 setup.py --version).tar.gz'"
  get-current-version:
  - "python3 setup.py --version"

jobs:
- job: sync_from_downstream
  trigger: commit

- job: propose_downstream
  trigger: release
  metadata:
    dist-git-branch: fedora-all

- job: copr_build
  trigger: pull_request
  metadata:
    targets: fedora-all
